-- MySQL Script generated by MySQL Workbench
-- Sat Dec 16 17:15:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Computer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Computer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(50) NOT NULL,
  `model` VARCHAR(50) NOT NULL,
  `is_upgradable` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RAM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RAM` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `capacity` INT NULL,
  `Computer_computer_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Computer_computer_id`),
  INDEX `fk_RAM_Computer1_idx` (`Computer_computer_id` ASC) ,
  CONSTRAINT `fk_RAM_Computer1`
    FOREIGN KEY (`Computer_computer_id`)
    REFERENCES `mydb`.`Computer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mouse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NOT NULL,
  `is_configurable` TINYINT NOT NULL,
  `Computer_computer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Mouse_Computer1_idx` (`Computer_computer_id` ASC) ,
  CONSTRAINT `fk_Mouse_Computer1`
    FOREIGN KEY (`Computer_computer_id`)
    REFERENCES `mydb`.`Computer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Monitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Monitor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `is_power_on` TINYINT NOT NULL,
  `Computer_computer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Monitor_Computer1_idx` (`Computer_computer_id` ASC) ,
  CONSTRAINT `fk_Monitor_Computer1`
    FOREIGN KEY (`Computer_computer_id`)
    REFERENCES `mydb`.`Computer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Keyboard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Keyboard` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `Computer_computer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Keyboard_Computer1_idx` (`Computer_computer_id` ASC) ,
  CONSTRAINT `fk_Keyboard_Computer1`
    FOREIGN KEY (`Computer_computer_id`)
    REFERENCES `mydb`.`Computer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Component`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Component` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GPU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GPU` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `memory` INT NOT NULL,
  `boost_cloock` INT NOT NULL,
  `Component_id` INT NOT NULL,
  `Computer_computer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_GPU_Component1_idx` (`Component_id` ASC) ,
  INDEX `fk_GPU_Computer1_idx` (`Computer_computer_id` ASC) ,
  CONSTRAINT `fk_GPU_Component1`
    FOREIGN KEY (`Component_id`)
    REFERENCES `mydb`.`Component` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GPU_Computer1`
    FOREIGN KEY (`Computer_computer_id`)
    REFERENCES `mydb`.`Computer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CPU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CPU` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `manufacturer` VARCHAR(45) NOT NULL,
  `speed` DOUBLE NOT NULL,
  `Component_id` INT NOT NULL,
  `Computer_computer_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Computer_computer_id`),
  INDEX `fk_CPU_Component1_idx` (`Component_id` ASC) ,
  INDEX `fk_CPU_Computer1_idx` (`Computer_computer_id` ASC) ,
  CONSTRAINT `fk_CPU_Component1`
    FOREIGN KEY (`Component_id`)
    REFERENCES `mydb`.`Component` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_CPU_Computer1`
    FOREIGN KEY (`Computer_computer_id`)
    REFERENCES `mydb`.`Computer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Desktop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Desktop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `form_factor` VARCHAR(45) NOT NULL,
  `Computer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Desktop_Computer1_idx` (`Computer_id` ASC) ,
  CONSTRAINT `fk_Desktop_Computer1`
    FOREIGN KEY (`Computer_id`)
    REFERENCES `mydb`.`Computer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Laptop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Laptop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `battery_life_in_hours` INT NOT NULL,
  `Computer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Laptop_Computer1_idx` (`Computer_id` ASC) ,
  CONSTRAINT `fk_Laptop_Computer1`
    FOREIGN KEY (`Computer_id`)
    REFERENCES `mydb`.`Computer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tablet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tablet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `has_touch_pen` TINYINT NOT NULL,
  `Computer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Tablet_Computer1_idx` (`Computer_id` ASC) ,
  CONSTRAINT `fk_Tablet_Computer1`
    FOREIGN KEY (`Computer_id`)
    REFERENCES `mydb`.`Computer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Os`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Os` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `os_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;