-- MySQL Script generated by MySQL Workbench
-- Thu Dec 14 08:58:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`RAM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RAM` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `capacity` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mouse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NOT NULL,
  `is_configurable` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Component`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Component` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GPU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GPU` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `memory` INT NOT NULL,
  `boost_cloock` INT NOT NULL,
  `Component_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_GPU_Component1_idx` (`Component_id` ASC),
  CONSTRAINT `fk_GPU_Component1`
    FOREIGN KEY (`Component_id`)
    REFERENCES `mydb`.`Component` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CPU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CPU` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `manufacturer` VARCHAR(45) NOT NULL,
  `speed` DOUBLE NOT NULL,
  `Component_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CPU_Component1_idx` (`Component_id` ASC),
  CONSTRAINT `fk_CPU_Component1`
    FOREIGN KEY (`Component_id`)
    REFERENCES `mydb`.`Component` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Monitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Monitor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `is_power_on` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Keyboard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Keyboard` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Desktop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Desktop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `form_factor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Laptop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Laptop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `battery_life_in_hours` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tablet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tablet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `has_touch_pen` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Computer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Computer` (
  `computer_id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(50) NOT NULL,
  `model` VARCHAR(50) NOT NULL,
  `is_upgradable` TINYINT NULL,
  `RAM_id` INT NOT NULL,
  `Mouse_id` INT NOT NULL,
  `GPU_id` INT NOT NULL,
  `CPU_id` INT NOT NULL,
  `Monitor_id` INT NOT NULL,
  `Keyboard_id` INT NOT NULL,
  `Desktop_id` INT NOT NULL,
  `Laptop_id` INT NOT NULL,
  `Tablet_id` INT NOT NULL,
  PRIMARY KEY (`computer_id`),
  INDEX `fk_Computer_RAM_idx` (`RAM_id` ASC),
  INDEX `fk_Computer_Mouse1_idx` (`Mouse_id` ASC),
  INDEX `fk_Computer_GPU1_idx` (`GPU_id` ASC),
  INDEX `fk_Computer_CPU1_idx` (`CPU_id` ASC),
  INDEX `fk_Computer_Monitor1_idx` (`Monitor_id` ASC),
  INDEX `fk_Computer_Keyboard1_idx` (`Keyboard_id` ASC),
  INDEX `fk_Computer_Desktop1_idx` (`Desktop_id` ASC),
  INDEX `fk_Computer_Laptop1_idx` (`Laptop_id` ASC),
  INDEX `fk_Computer_Tablet1_idx` (`Tablet_id` ASC),
  CONSTRAINT `fk_Computer_RAM`
    FOREIGN KEY (`RAM_id`)
    REFERENCES `mydb`.`RAM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Computer_Mouse1`
    FOREIGN KEY (`Mouse_id`)
    REFERENCES `mydb`.`Mouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Computer_GPU1`
    FOREIGN KEY (`GPU_id`)
    REFERENCES `mydb`.`GPU` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Computer_CPU1`
    FOREIGN KEY (`CPU_id`)
    REFERENCES `mydb`.`CPU` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Computer_Monitor1`
    FOREIGN KEY (`Monitor_id`)
    REFERENCES `mydb`.`Monitor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Computer_Keyboard1`
    FOREIGN KEY (`Keyboard_id`)
    REFERENCES `mydb`.`Keyboard` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Computer_Desktop1`
    FOREIGN KEY (`Desktop_id`)
    REFERENCES `mydb`.`Desktop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Computer_Laptop1`
    FOREIGN KEY (`Laptop_id`)
    REFERENCES `mydb`.`Laptop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Computer_Tablet1`
    FOREIGN KEY (`Tablet_id`)
    REFERENCES `mydb`.`Tablet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Os`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Os` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `os_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;